[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ianlaw", email = "lawmankiian@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "anthropic>=1.8.0",
    "fastapi>=0.141.1",
    "lightgbm>=4.7.0",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "scikit-learn>=1.9.1",
    "shapely>=2.1.2",
    "uvicorn>=0.54.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
